#@see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Indexer Workflow
on:
  schedule:
    - cron:  '*/30 * * * *'
jobs:
  indexer-run:
    name: indexer-tests
    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Make
        run: make