#@see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Indexer Workflow
on:
  schedule:
    - cron:  '*/10 * * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Make
      run: |
        git reset --hard b0f52ce743c1dfd4f43961eb6088ebc9550d0582
        git rebase develop    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build  
      run: python ./start.py > docs/index.md;
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Github action
        author_email: build-no-reply@github.com
        message: "Updated News"
        add: "docs/index.md"
      env:
        GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}